#-------------------------------
# Site Settings
title: Lena Schneider Fotografie
logo: # You can add own logo. For example '/images/logo.png'.
description: Hilton is a super simple portfolio theme for Jekyll.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Pakete'
      url: '/pakete/'
    - title: 'Portfolio'
      url: '/portfolios/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Mehr'
      submenu:
      - url: '/about/'
        title: 'Über Mich'
      - url: '/contact/'
        title: 'Kontakt'
      - url: '/impressum/'
        title: 'Impressum'


#-------------------------------
# Author Settings
author:
  author__name: Lena Schneider
  author__bio: 'Ich bin Lena. 28 Jahre, Mama, Hundemama und Ehefrau.

  <br></br>
  Bei jeder Nachricht die bei mir eintrudelt hüpft mein Herz vor Vorfreude und Aufregung. 
  Ich bin ein offener, ehrlicher Mensch und finde es spannend neue Persönlichkeiten kennenzulernen. 
  Ebenso bin ich auch ein sehr emotionaler Mensch, nehme mir vieles zu Herzen und mache mir viele Gedanken. 
  Das ist Fluch und Segen zugleich.
  Wenn ich allerdings meiner Leidenschaft nachgehen kann, sehe ich in jeder Begegnung eine Chance, Freude zu teilen und positive Energie zu verbreiten.'

  author__avatar: '/images/lena.jpg'

social:
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/lenaschneider_fotografie/"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, ich bin Lena.
  hero__description: 
    Eure Fotografin mit einer Leidenschaft für die Einzigartigkeit von Menschen und Familien. 
    <br></br>
    Für mich sind nicht nur Fotos, sondern auch die Geschichten hinter den Beziehungen von unschätzbarem Wert. 
    Jede Familie hat eine einzigartige Geschichte, von den ersten Tagen einer jungen Familie bis zu den gemeinsam verbrachten Jahren. 
    Diese inspirieren mich und spiegeln sich in meinen Fotografien wieder.
    
  hero__image: '/images/lena.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address...
mailchimp__button__text: Get updates


#-------------------------------
# Pakete Settings
pakete__settings:
  pakete__title: Deine Geschichte - meine Pakete 
  pakete__description:

#-------------------------------
# Portfolio Settings
portfolio__settings:
  portfolio__title: Portfolio
  portfolio__description: Mehr Eindrücke zu meinem Stil

#-------------------------------
# Testimonials Section
testimonial__title: What clients say
testimonial__description:

testimonial__items:
  - name: "Martina S."
    image: "/images/client-1.jpg"
    designation: "Schwangerschaft"
    content : "Ich kann das Babybauchshooting nur weiterempfehlen. Lena ist eine super nette & professionelle Fotografin, die mit viel Geduld & Liebe fürs Detail dabei ist!
Lena hat eine tolle Atmosphäre geschaffen, in der ich mich gleich wohl gefühlt habe. Lieben Dank für die wunderschönen Bilder!"

  - name: "Anna L."
    image: "/images/client-2.jpg"
    designation: "Familien"
    content : "Wir hatten jetzt schon zwei Familienshootings bei der lieben Lena. Mein Mann und ich sind beide etwas unbeholfen vor der Kamera, aber Lena bringt so eine Gelassenheit und Freude mit, dass das überhaupt kein Problem mehr war. Wir haben uns super wohl gefühlt bei den Shootings, und auch mit unserem Zwerg ist sie ganz toll umgegangen. Lena hat ein wundervolles Auge für  Details und die kleinen schönen Momente, die einfach so passieren, ohne, dass man sich in Posen zwingen muss. Wir sind super happy mit den Bildern und werden auch in Zukunft sicher weitere Shootings buchen."

  - name: "Martina S."
    image: "/images/client-3.jpg"
    designation: "Newborn Homestory"
    content : "Ich hab mich sehr gefreut, dass Lena auch das Neugeborenen Shooting unserer Sohnes gemacht hat. Unser Sohn hat sich sehr wohl gefühlt & es wurden süße Bilder im Alltag einer frisch gebackenen Familie gemacht. Lieben Dank dir!"

  - name: "Anika Calzoni"
    image: "/images/client-4.jpg"
    designation: "Lettering Artist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Marcus Botosh"
    image: "/images/client-5.jpg"
    designation: "Full Stack Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog__settings:
  blog__title: Recent Posts
  blog__description:


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/footer_gallery/footer-1.jpg'
    - alt: 'Lifestyle'
      url: '/images/footer_gallery/footer-2.jpg'
    - alt: 'Hobby'
      url: '/images/footer_gallery/footer-3.jpg'
    - alt: 'Notes'
      url: '/images/footer_gallery/footer-4.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Pakete'
      url: '/pakete/'
    - title: 'Portfolio'
      url: '/portfolios/'
    - title: 'Blog'
      url: '/blog/'
    - url: '/about/'
      title: 'Über Mich'
    - url: '/contact/'
      title: 'Kontakt'
    - url: '/impressum/'
      title: 'Impressum'


#-------------------------------
# Contact Settings
contact:
  email: info@lenaschneider.photography # Add your form_id
  handy: 01759620258
  description: Hilton comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id